// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCozwRAgTEdYB5vgbuxJO9wrdH2cfNZGIg',
    appId: '1:140424544275:web:f0bab2bbeaf33fb64d3fe6',
    messagingSenderId: '140424544275',
    projectId: 'helthy-a2c57',
    authDomain: 'helthy-a2c57.firebaseapp.com',
    storageBucket: 'helthy-a2c57.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAObq5PzgV7jpWATMeXFV8fVxa-xqAd7JQ',
    appId: '1:140424544275:android:7eba0b919358d13a4d3fe6',
    messagingSenderId: '140424544275',
    projectId: 'helthy-a2c57',
    storageBucket: 'helthy-a2c57.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYFHpft6nA-zw_BPa7c5toPOudXL37AUw',
    appId: '1:140424544275:ios:189f41f1678a023a4d3fe6',
    messagingSenderId: '140424544275',
    projectId: 'helthy-a2c57',
    storageBucket: 'helthy-a2c57.firebasestorage.app',
    iosBundleId: 'com.helthy.app',
  );
}
